# Generated by Django 4.0.5 on 2022-06-09 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='fechaPublicacion',
            field=models.DateField(default=datetime.datetime(2022, 6, 9, 12, 12, 18, 194125)),
        ),
    ]
