# Generated by Django 4.0.5 on 2022-06-09 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_foto_fechapublicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='fechaPublicacion',
            field=models.DateField(default=datetime.datetime(2022, 6, 9, 12, 30, 32, 165876)),
        ),
    ]
